server {
    listen 80 reuseport;
    set $lancache_status "MISS";

    underscores_in_headers on;

    access_log /data/logs/nginx-access.log cachelog if=$loggable;
    error_log /data/logs/nginx-error.log;

    include http.d/conf.d/*.conf;
}
