root /data/storage;

location / {
    error_page 301 =200 @download_from_storage;
    error_page 404 =200 @download_from_host;

    proxy_pass http://LANCACHE_HOST:3128$request_uri;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass_header *;
    proxy_intercept_errors on;
}
