location @download_from_storage {
    internal;
    set $file_path $upstream_http_location;
    set $lancache_status "HIT";

    add_header Location "";
    add_header X-Lancache-Status $lancache_status;
    add_header X-Upstream-location $upstream_http_location;
    add_header X-Upstream-status $upstream_status;

    try_files $file_path @download_from_host;
}

location @download_from_host {
    internal;
    set $lancache_status "MISS";

    add_header X-Lancache-Status $lancache_status;
    add_header X-Upstream_status $upstream_status;

    proxy_pass http://$host$request_uri;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
}
